### ISSUE TITLE
Tutorial 5 - 3-D Topography (Planetary / Antarctic Maps)

### ISSUE THREAD

**Issue by weiji14** [GenericMappingTools/agu24workshop#11]
Starting a thread for me and @andrebelem to discuss about what to do for the 3-D Topography tutorial!

Concepts to cover:
- [`grdview`](https://www.pygmt.org/v0.13.0/api/generated/pygmt.Figure.grdview.html)
- [`pygmt.datasets.load_*_relief`](https://www.pygmt.org/v0.13.0/api/index.html#datasets)

Initial ideas:
- 3-D Antarctic maps from https://github.com/andrebelem/3D-Antarctic-maps (see also https://forum.generic-mapping-tools.org/t/some-3d-maps-using-pygmt-and-the-new-ibcso-data/3017)
- Mars maps based on egu22pygmt tutorial originally created at https://github.com/GenericMappingTools/egu22pygmt/pull/15

**Comment by andrebelem** [comment]
@weiji14

I've made some upgrades and updates to [PlanetaryMaps](https://github.com/andrebelem/PlanetaryMaps), including an explanation on how to use `grdview`. I recently used these notebooks here at the university to demonstrate `grdview`, and it worked well within a 20-minute class.

Regarding the `pygmt.datasets.load_*_relief`, we could incorporate one of the 3D Antarctic maps, though it relies on the IBCSO V2 dataset, which isn’t part of the `datasets.load_*_relief` package. What’s your suggestion? Should we use a simple 3D relief to compare with IBCSO, or do you think that might be too complex for this course?

**Comment by weiji14** [comment]
> I've made some upgrades and updates to [PlanetaryMaps](https://github.com/andrebelem/PlanetaryMaps), including an explanation on how to use `grdview`. I recently used these notebooks here at the university to demonstrate `grdview`, and it worked well within a 20-minute class.

Nice, I'll need to check that out again! If you don't mind, I can adapt that Planetary Maps tutorial of yours, and maybe just use GMT's built-in https://www.generic-mapping-tools.org/remote-datasets/mars-relief.html dataset (added as `pygmt.datasets.load_mars_relief` since PyGMT v0.11.0, https://github.com/GenericMappingTools/pygmt/pull/2847)

> Regarding the `pygmt.datasets.load_*_relief`, we could incorporate one of the 3D Antarctic maps, though it relies on the IBCSO V2 dataset, which isn’t part of the `datasets.load_*_relief` package. What’s your suggestion? Should we use a simple 3D relief to compare with IBCSO, or do you think that might be too complex for this course?

I think it would be useful to show how to load DEMs outside of `pygmt.datasets.load_*_relief`, e.g. from GeoTIFF or NetCDF files, though unsure if @maxrjones will want to cover this in Tutorial 3 (xarray). I've not used IBCSO before, but could take a look, or otherwise choose other Antarctic datasets I'm more familiar with (e.g [REMA](https://www.pgc.umn.edu/data/rema/)).

**Comment by joa-quim** [comment]
> I think it would be useful to show how to load DEMs outside of pygmt.datasets.load_*_relief, e.g. from GeoTIFF or NetCDF files, though unsure if @maxrjones will want to cover this in Tutorial 3 (xarray). 

Again, since I receive these messages, one thing it puzzles me for a long time (well, two in fact)

- Why do you need a function for each different dataset. Why not just one that can read them all?
- When dealing with disk files, why not let GMT do the file reading directly instead of loading them first (memory and resources potentially demanding) and next put the conversion machinery in work to send the data to GMT that could have done same in a much more efficient way?

**Comment by weiji14** [comment]
> Why do you need a function for each different dataset. Why not just one that can read them all?

This can be discussed at https://github.com/GenericMappingTools/pygmt/issues/2431. We do have a single function for sample tabular datasets, see https://github.com/GenericMappingTools/pygmt/issues/2302. But for the planetary datasets, we created different ones, probably to allow for tab-completion :wink:

> * When dealing with disk files, why not let GMT do the file reading directly instead of loading them first (memory and resources potentially demanding) and next put the conversion machinery in work to send the data to GMT that could have done same in a much more efficient way?

For disk files yes, we can read the file directly. For non-disk files over a network, or other file formats not supported by GMT yet (e.g. Zarr, HDF5 files that are not NetCDF, FITS, etc), we can use xarray or other libraries to read into memory first, perform operations such as subsetting, NaN removal, etc before passing into GMT for plotting.

Going back to the topic here, REMA for example is available over s3 cloud storage at https://registry.opendata.aws/pgc-rema/, so we can potentially access that over the network, subset it to a region we want, and then plot it via `grdview`.

**Comment by joa-quim** [comment]
- Point 1) Not convinced that over-complication compensates tab-completion, but I don't need be 😃 
- Point 2) I do read those all in GMT.jl with `gmtread` but I know that I have the advantage to be able to access the deeper guts of the GMT lib directly. Remote netcdf can only be read remotely with GDAL in Linux. But the examples that I have seen you guys using are mostly the remote datasets. And those, again, can be read directly by GMT.

**Comment by andrebelem** [comment]
Hi @weiji14 
> Nice, I'll need to check that out again! If you don't mind, I can adapt that Planetary Maps tutorial of yours...

Yes! It would be fantastic to adapt `pygmt.datasets.load_mars_relief`. When I started this notebook, I believe it was on an older version, and since I often run things without internet while on the ship, I got used to using local disk resources. I do need to update PlanetaryMaps to reflect this !

>  I've not used IBCSO before, but could take a look, or otherwise choose other Antarctic datasets I'm more familiar with (e.g [REMA](https://www.pgc.umn.edu/data/rema/)).

I also agree that REMA is a better choice for smaller scales. I'm working on finalizing an example of using a GeoTIFF from Google Earth Engine as a drape over a DEM (REMA) on Paulet Island. If I manage to complete it, we could include it as well. There are some interesting DEMs available via GEE that we could try out together. The IBCSO is indeed a "giant"!

I’m really interested in trying the pseudo-DEM of Noctis Labyrinthus (check out [this topographic map](https://www.dlr.de/en/latest/news/2024/dlr-s-mars-camera-20-years-of-operations/topographical-map-of-the-eastern-part-of-noctis-labyrinthus)), but I haven’t found the time to dive into it yet. I think what we already have prepared will be enough for the AGU course, and we can add more to External Resources later. I’d also like to prepare something on Europa (thinking of the Europa Clipper mission), and I imagine that in the coming years, more and more researchers in Planetary Sciences will start using these maps. Maybe we can aim for EGU25 or 26?

Thanks again !

**Comment by weiji14** [comment]
> > Nice, I'll need to check that out again! If you don't mind, I can adapt that Planetary Maps tutorial of yours...
> 
> Yes! It would be fantastic to adapt `pygmt.datasets.load_mars_relief`. When I started this notebook, I believe it was on an older version, and since I often run things without internet while on the ship, I got used to using local disk resources. I do need to update PlanetaryMaps to reflect this !
> 
> > I've not used IBCSO before, but could take a look, or otherwise choose other Antarctic datasets I'm more familiar with (e.g [REMA](https://www.pgc.umn.edu/data/rema/)).
> 
> I also agree that REMA is a better choice for smaller scales. I'm working on finalizing an example of using a GeoTIFF from Google Earth Engine as a drape over a DEM (REMA) on Paulet Island. If I manage to complete it, we could include it as well. There are some interesting DEMs available via GEE that we could try out together. The IBCSO is indeed a "giant"!

Cool, I think we've got a plan, so we'll do something like:

1. Planetary map of Mars - just `grdview` perspective plot with a built-in colormap
2. 3-D Antarctic map - `grdview` perspective plot with an RGB overlay (I made one [over Scott Base with a Sentinel-2 ovelay](https://github.com/weiji14/30DayMapChallenge2021/blob/main/day11_3d.py) before)

I can start working on this over the next few days, hopefully can get a first draft ready by 20 November for review.

> I’d also like to prepare something on Europa (thinking of the Europa Clipper mission), and I imagine that in the coming years, more and more researchers in Planetary Sciences will start using these maps. Maybe we can aim for EGU25 or 26?

I think the short course deadline for EGU25 has passed already, so probably wait for EGU26 :slightly_smiling_face:

**Comment by andrebelem** [comment]
> 2. 3-D Antarctic map - `grdview` perspective plot with an RGB overlay (I made one [over Scott Base with a Sentinel-2 ovelay](https://github.com/weiji14/30DayMapChallenge2021/blob/main/day11_3d.py) before)

Super cool ! 😎
